//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Settings/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""Gameplay"",
            ""id"": ""4fbc26d3-ee48-4b5b-b0f7-a97aeeebd515"",
            ""actions"": [
                {
                    ""name"": ""Axes"",
                    ""type"": ""Value"",
                    ""id"": ""73e4fbf4-bda5-489b-94c5-142bb4e24027"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Run"",
                    ""type"": ""Button"",
                    ""id"": ""70bef157-ebcb-4ffa-90e2-254d273e2f1b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Attack"",
                    ""type"": ""Button"",
                    ""id"": ""38401311-5429-4a60-8ffb-38ed4c08efec"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchCharacter1"",
                    ""type"": ""Button"",
                    ""id"": ""e888d136-30f7-4963-978f-1837d42d8f3f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchCharacter2"",
                    ""type"": ""Button"",
                    ""id"": ""4ad02343-8fef-43eb-a1d0-10a7e193ed7b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchCharacter3"",
                    ""type"": ""Button"",
                    ""id"": ""2b361537-094b-42dd-b0b6-6da25c08311d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dodge"",
                    ""type"": ""Button"",
                    ""id"": ""a5e5e276-a4cc-4c87-9956-43a28062571d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Guard"",
                    ""type"": ""Button"",
                    ""id"": ""ea8dcf16-7b4d-4e4b-9852-679c1dfffa34"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Skill1"",
                    ""type"": ""Button"",
                    ""id"": ""fbd01cf8-82df-49eb-acda-1e2922e0418e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Skill2"",
                    ""type"": ""Button"",
                    ""id"": ""26e166e4-c234-49b9-a45b-5cac2f44930a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""USkill"",
                    ""type"": ""Button"",
                    ""id"": ""bbd5665e-71d1-4aed-960d-add16e34697b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AimAxes"",
                    ""type"": ""Value"",
                    ""id"": ""5be76879-04f1-4eb4-962f-7ba735de24d4"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SwitchFunctionkey4"",
                    ""type"": ""Button"",
                    ""id"": ""4fc0f8f3-54a9-420f-96fe-04af612de24f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchFunctionkey3"",
                    ""type"": ""Button"",
                    ""id"": ""ab5a6034-70f3-4af2-947c-95e8b3b4e64b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchFunctionkey2"",
                    ""type"": ""Button"",
                    ""id"": ""b0c9bb7b-4e4a-4dea-8a65-db28a8f109bd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchFunctionkey1"",
                    ""type"": ""Button"",
                    ""id"": ""9dda4cbb-b617-4ee6-95b3-eecf12fdcafb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ReadyFunctionKey"",
                    ""type"": ""Button"",
                    ""id"": ""6234294b-d568-4bc0-9437-5044096c880c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""b4983db6-f51b-4ff4-bb5f-7c221e38ebd1"",
                    ""path"": ""2DVector(mode=1)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Axes"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""d4958eec-6a7f-4762-9a22-068b405a9602"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Axes"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""94ed3aec-9719-4896-91b2-40a51406b91b"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Axes"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""77cbab1a-0731-4bd9-8232-81289527121c"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Axes"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""04c7c6c8-5243-4f75-a674-629d2425281c"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Axes"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Arrows"",
                    ""id"": ""738161ba-e20c-426d-bd15-c5312d56ee48"",
                    ""path"": ""2DVector(mode=1)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Axes"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""0b961c10-b353-40f4-9835-e53bac989659"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Axes"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""dbece024-4733-4ac7-9ec8-ae435a957990"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Axes"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""279173db-3226-4422-b923-07e950a79313"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Axes"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""4a08cb0f-1abe-48ca-8d77-3fe78ee0d127"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Axes"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""LeftStick"",
                    ""id"": ""ab39c2ae-8f03-47ea-87e3-e1803b377801"",
                    ""path"": ""2DVector(mode=1)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Axes"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""f624790a-0a2a-49c4-ab32-3b697a41d4b7"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Axes"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""37804e6a-6dc6-49c4-811e-8c065451e0a2"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Axes"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""c69ef620-ed54-4da2-a9f7-6d7db32806cd"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Axes"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""0c6d13fe-9b7c-4019-a3c7-b949d626e1c7"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Axes"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""173c20e1-7dc5-40af-91aa-fa99993b06a2"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3ab6af44-7c25-4d28-ad20-4eebd6d513fa"",
                    ""path"": ""<XInputController>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e9a9d2fc-c3ee-44f0-abe2-e0b996f042f0"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9e523b1f-395f-4394-a24d-894d07205520"",
                    ""path"": ""<XInputController>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""87459ee3-435f-49a9-920b-013bb877cba1"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchCharacter1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0ce1a5ec-e29a-4f97-8906-41149aba249e"",
                    ""path"": ""<XInputController>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchCharacter1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8ce69bcd-75b5-4f50-a8e7-1f776c84fd4c"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchCharacter2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a96dc2cc-de9a-4e3c-bdad-9fe7e14b9817"",
                    ""path"": ""<XInputController>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchCharacter2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1078c209-4236-49b0-b405-e40aa9697fc2"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchCharacter3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a87ec5ba-fd03-4fd3-97c4-20460068b0d2"",
                    ""path"": ""<XInputController>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchCharacter3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7e192172-1631-477e-9480-2bf44b8175f9"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dodge"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ade46346-8978-454e-93c6-6a75b3d40497"",
                    ""path"": ""<XInputController>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dodge"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d880058a-44dd-4a98-8e3d-e81cbd1d9b66"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Skill1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f34575be-f9a8-40f2-934a-193f44721cbb"",
                    ""path"": ""<XInputController>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Skill1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6a5db270-d094-4351-a750-b2b1b12e4c8d"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Skill2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e830eeb6-173a-4850-937e-2a38fe1e7660"",
                    ""path"": ""<XInputController>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Skill2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2e84494e-4b04-45d5-9998-edeb09be6d86"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AimAxes"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""af64f963-b101-4d8b-bfdb-dd813aeb411c"",
                    ""path"": ""<XInputController>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AimAxes"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2d37b5f6-cd27-4131-bb0c-336ec796f93b"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Guard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""279002c7-56c2-4d47-8433-90e439361803"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""USkill"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""f7054d1a-550c-4222-8e4b-69830ca5d531"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchFunctionkey4"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""23d259af-c8c5-45d6-9dc5-aeee43611499"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchFunctionkey4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""fd91aae2-24c2-43b6-bba2-bd2470863aab"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchFunctionkey4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""65bd80ae-091c-4418-bfe7-34a133fcfbdb"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchFunctionkey3"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""ce461871-fea4-4361-8c58-e5b1134c18ef"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchFunctionkey3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""b2988117-f64d-4b28-9d2c-a65888fb794e"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchFunctionkey3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""79235867-2a7b-4391-8dec-a2f315785a0c"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchFunctionkey2"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""ab83f3fa-2fa5-424b-97fe-cef4130c880e"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchFunctionkey2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""759d9d8d-e184-4c61-92b2-695a3a98dffe"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchFunctionkey2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""6ef57b5f-2968-49fa-ab86-724e3dc8629c"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchFunctionkey1"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""27aa4282-ba26-42e7-997c-f2b0b3bf32ef"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchFunctionkey1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""22a8d63e-e6fc-4f9f-84a7-0c9bab238c71"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchFunctionkey1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""fdbebf56-cfe3-4577-8d7d-424a206d1121"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ReadyFunctionKey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""control scheme1"",
            ""bindingGroup"": ""control scheme1"",
            ""devices"": [
                {
                    ""devicePath"": ""<XInputController>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Gameplay
        m_Gameplay = asset.FindActionMap("Gameplay", throwIfNotFound: true);
        m_Gameplay_Axes = m_Gameplay.FindAction("Axes", throwIfNotFound: true);
        m_Gameplay_Run = m_Gameplay.FindAction("Run", throwIfNotFound: true);
        m_Gameplay_Attack = m_Gameplay.FindAction("Attack", throwIfNotFound: true);
        m_Gameplay_SwitchCharacter1 = m_Gameplay.FindAction("SwitchCharacter1", throwIfNotFound: true);
        m_Gameplay_SwitchCharacter2 = m_Gameplay.FindAction("SwitchCharacter2", throwIfNotFound: true);
        m_Gameplay_SwitchCharacter3 = m_Gameplay.FindAction("SwitchCharacter3", throwIfNotFound: true);
        m_Gameplay_Dodge = m_Gameplay.FindAction("Dodge", throwIfNotFound: true);
        m_Gameplay_Guard = m_Gameplay.FindAction("Guard", throwIfNotFound: true);
        m_Gameplay_Skill1 = m_Gameplay.FindAction("Skill1", throwIfNotFound: true);
        m_Gameplay_Skill2 = m_Gameplay.FindAction("Skill2", throwIfNotFound: true);
        m_Gameplay_USkill = m_Gameplay.FindAction("USkill", throwIfNotFound: true);
        m_Gameplay_AimAxes = m_Gameplay.FindAction("AimAxes", throwIfNotFound: true);
        m_Gameplay_SwitchFunctionkey4 = m_Gameplay.FindAction("SwitchFunctionkey4", throwIfNotFound: true);
        m_Gameplay_SwitchFunctionkey3 = m_Gameplay.FindAction("SwitchFunctionkey3", throwIfNotFound: true);
        m_Gameplay_SwitchFunctionkey2 = m_Gameplay.FindAction("SwitchFunctionkey2", throwIfNotFound: true);
        m_Gameplay_SwitchFunctionkey1 = m_Gameplay.FindAction("SwitchFunctionkey1", throwIfNotFound: true);
        m_Gameplay_ReadyFunctionKey = m_Gameplay.FindAction("ReadyFunctionKey", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Gameplay
    private readonly InputActionMap m_Gameplay;
    private IGameplayActions m_GameplayActionsCallbackInterface;
    private readonly InputAction m_Gameplay_Axes;
    private readonly InputAction m_Gameplay_Run;
    private readonly InputAction m_Gameplay_Attack;
    private readonly InputAction m_Gameplay_SwitchCharacter1;
    private readonly InputAction m_Gameplay_SwitchCharacter2;
    private readonly InputAction m_Gameplay_SwitchCharacter3;
    private readonly InputAction m_Gameplay_Dodge;
    private readonly InputAction m_Gameplay_Guard;
    private readonly InputAction m_Gameplay_Skill1;
    private readonly InputAction m_Gameplay_Skill2;
    private readonly InputAction m_Gameplay_USkill;
    private readonly InputAction m_Gameplay_AimAxes;
    private readonly InputAction m_Gameplay_SwitchFunctionkey4;
    private readonly InputAction m_Gameplay_SwitchFunctionkey3;
    private readonly InputAction m_Gameplay_SwitchFunctionkey2;
    private readonly InputAction m_Gameplay_SwitchFunctionkey1;
    private readonly InputAction m_Gameplay_ReadyFunctionKey;
    public struct GameplayActions
    {
        private @PlayerInputActions m_Wrapper;
        public GameplayActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Axes => m_Wrapper.m_Gameplay_Axes;
        public InputAction @Run => m_Wrapper.m_Gameplay_Run;
        public InputAction @Attack => m_Wrapper.m_Gameplay_Attack;
        public InputAction @SwitchCharacter1 => m_Wrapper.m_Gameplay_SwitchCharacter1;
        public InputAction @SwitchCharacter2 => m_Wrapper.m_Gameplay_SwitchCharacter2;
        public InputAction @SwitchCharacter3 => m_Wrapper.m_Gameplay_SwitchCharacter3;
        public InputAction @Dodge => m_Wrapper.m_Gameplay_Dodge;
        public InputAction @Guard => m_Wrapper.m_Gameplay_Guard;
        public InputAction @Skill1 => m_Wrapper.m_Gameplay_Skill1;
        public InputAction @Skill2 => m_Wrapper.m_Gameplay_Skill2;
        public InputAction @USkill => m_Wrapper.m_Gameplay_USkill;
        public InputAction @AimAxes => m_Wrapper.m_Gameplay_AimAxes;
        public InputAction @SwitchFunctionkey4 => m_Wrapper.m_Gameplay_SwitchFunctionkey4;
        public InputAction @SwitchFunctionkey3 => m_Wrapper.m_Gameplay_SwitchFunctionkey3;
        public InputAction @SwitchFunctionkey2 => m_Wrapper.m_Gameplay_SwitchFunctionkey2;
        public InputAction @SwitchFunctionkey1 => m_Wrapper.m_Gameplay_SwitchFunctionkey1;
        public InputAction @ReadyFunctionKey => m_Wrapper.m_Gameplay_ReadyFunctionKey;
        public InputActionMap Get() { return m_Wrapper.m_Gameplay; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameplayActions set) { return set.Get(); }
        public void SetCallbacks(IGameplayActions instance)
        {
            if (m_Wrapper.m_GameplayActionsCallbackInterface != null)
            {
                @Axes.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnAxes;
                @Axes.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnAxes;
                @Axes.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnAxes;
                @Run.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnRun;
                @Run.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnRun;
                @Run.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnRun;
                @Attack.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnAttack;
                @Attack.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnAttack;
                @Attack.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnAttack;
                @SwitchCharacter1.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSwitchCharacter1;
                @SwitchCharacter1.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSwitchCharacter1;
                @SwitchCharacter1.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSwitchCharacter1;
                @SwitchCharacter2.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSwitchCharacter2;
                @SwitchCharacter2.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSwitchCharacter2;
                @SwitchCharacter2.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSwitchCharacter2;
                @SwitchCharacter3.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSwitchCharacter3;
                @SwitchCharacter3.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSwitchCharacter3;
                @SwitchCharacter3.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSwitchCharacter3;
                @Dodge.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnDodge;
                @Dodge.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnDodge;
                @Dodge.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnDodge;
                @Guard.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnGuard;
                @Guard.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnGuard;
                @Guard.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnGuard;
                @Skill1.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSkill1;
                @Skill1.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSkill1;
                @Skill1.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSkill1;
                @Skill2.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSkill2;
                @Skill2.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSkill2;
                @Skill2.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSkill2;
                @USkill.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnUSkill;
                @USkill.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnUSkill;
                @USkill.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnUSkill;
                @AimAxes.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnAimAxes;
                @AimAxes.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnAimAxes;
                @AimAxes.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnAimAxes;
                @SwitchFunctionkey4.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSwitchFunctionkey4;
                @SwitchFunctionkey4.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSwitchFunctionkey4;
                @SwitchFunctionkey4.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSwitchFunctionkey4;
                @SwitchFunctionkey3.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSwitchFunctionkey3;
                @SwitchFunctionkey3.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSwitchFunctionkey3;
                @SwitchFunctionkey3.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSwitchFunctionkey3;
                @SwitchFunctionkey2.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSwitchFunctionkey2;
                @SwitchFunctionkey2.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSwitchFunctionkey2;
                @SwitchFunctionkey2.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSwitchFunctionkey2;
                @SwitchFunctionkey1.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSwitchFunctionkey1;
                @SwitchFunctionkey1.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSwitchFunctionkey1;
                @SwitchFunctionkey1.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSwitchFunctionkey1;
                @ReadyFunctionKey.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnReadyFunctionKey;
                @ReadyFunctionKey.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnReadyFunctionKey;
                @ReadyFunctionKey.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnReadyFunctionKey;
            }
            m_Wrapper.m_GameplayActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Axes.started += instance.OnAxes;
                @Axes.performed += instance.OnAxes;
                @Axes.canceled += instance.OnAxes;
                @Run.started += instance.OnRun;
                @Run.performed += instance.OnRun;
                @Run.canceled += instance.OnRun;
                @Attack.started += instance.OnAttack;
                @Attack.performed += instance.OnAttack;
                @Attack.canceled += instance.OnAttack;
                @SwitchCharacter1.started += instance.OnSwitchCharacter1;
                @SwitchCharacter1.performed += instance.OnSwitchCharacter1;
                @SwitchCharacter1.canceled += instance.OnSwitchCharacter1;
                @SwitchCharacter2.started += instance.OnSwitchCharacter2;
                @SwitchCharacter2.performed += instance.OnSwitchCharacter2;
                @SwitchCharacter2.canceled += instance.OnSwitchCharacter2;
                @SwitchCharacter3.started += instance.OnSwitchCharacter3;
                @SwitchCharacter3.performed += instance.OnSwitchCharacter3;
                @SwitchCharacter3.canceled += instance.OnSwitchCharacter3;
                @Dodge.started += instance.OnDodge;
                @Dodge.performed += instance.OnDodge;
                @Dodge.canceled += instance.OnDodge;
                @Guard.started += instance.OnGuard;
                @Guard.performed += instance.OnGuard;
                @Guard.canceled += instance.OnGuard;
                @Skill1.started += instance.OnSkill1;
                @Skill1.performed += instance.OnSkill1;
                @Skill1.canceled += instance.OnSkill1;
                @Skill2.started += instance.OnSkill2;
                @Skill2.performed += instance.OnSkill2;
                @Skill2.canceled += instance.OnSkill2;
                @USkill.started += instance.OnUSkill;
                @USkill.performed += instance.OnUSkill;
                @USkill.canceled += instance.OnUSkill;
                @AimAxes.started += instance.OnAimAxes;
                @AimAxes.performed += instance.OnAimAxes;
                @AimAxes.canceled += instance.OnAimAxes;
                @SwitchFunctionkey4.started += instance.OnSwitchFunctionkey4;
                @SwitchFunctionkey4.performed += instance.OnSwitchFunctionkey4;
                @SwitchFunctionkey4.canceled += instance.OnSwitchFunctionkey4;
                @SwitchFunctionkey3.started += instance.OnSwitchFunctionkey3;
                @SwitchFunctionkey3.performed += instance.OnSwitchFunctionkey3;
                @SwitchFunctionkey3.canceled += instance.OnSwitchFunctionkey3;
                @SwitchFunctionkey2.started += instance.OnSwitchFunctionkey2;
                @SwitchFunctionkey2.performed += instance.OnSwitchFunctionkey2;
                @SwitchFunctionkey2.canceled += instance.OnSwitchFunctionkey2;
                @SwitchFunctionkey1.started += instance.OnSwitchFunctionkey1;
                @SwitchFunctionkey1.performed += instance.OnSwitchFunctionkey1;
                @SwitchFunctionkey1.canceled += instance.OnSwitchFunctionkey1;
                @ReadyFunctionKey.started += instance.OnReadyFunctionKey;
                @ReadyFunctionKey.performed += instance.OnReadyFunctionKey;
                @ReadyFunctionKey.canceled += instance.OnReadyFunctionKey;
            }
        }
    }
    public GameplayActions @Gameplay => new GameplayActions(this);
    private int m_controlscheme1SchemeIndex = -1;
    public InputControlScheme controlscheme1Scheme
    {
        get
        {
            if (m_controlscheme1SchemeIndex == -1) m_controlscheme1SchemeIndex = asset.FindControlSchemeIndex("control scheme1");
            return asset.controlSchemes[m_controlscheme1SchemeIndex];
        }
    }
    public interface IGameplayActions
    {
        void OnAxes(InputAction.CallbackContext context);
        void OnRun(InputAction.CallbackContext context);
        void OnAttack(InputAction.CallbackContext context);
        void OnSwitchCharacter1(InputAction.CallbackContext context);
        void OnSwitchCharacter2(InputAction.CallbackContext context);
        void OnSwitchCharacter3(InputAction.CallbackContext context);
        void OnDodge(InputAction.CallbackContext context);
        void OnGuard(InputAction.CallbackContext context);
        void OnSkill1(InputAction.CallbackContext context);
        void OnSkill2(InputAction.CallbackContext context);
        void OnUSkill(InputAction.CallbackContext context);
        void OnAimAxes(InputAction.CallbackContext context);
        void OnSwitchFunctionkey4(InputAction.CallbackContext context);
        void OnSwitchFunctionkey3(InputAction.CallbackContext context);
        void OnSwitchFunctionkey2(InputAction.CallbackContext context);
        void OnSwitchFunctionkey1(InputAction.CallbackContext context);
        void OnReadyFunctionKey(InputAction.CallbackContext context);
    }
}
